databases:
  - name: chatscape
    databaseName: chatscape
    schema: chatscape
    user: chatscape

services:
  - type: web
    name: chatscape
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: chatscape
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false